version: '3.8'

services:
  mcp-web-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Server API
      - "3003:3003"  # Client web interface
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CLIENT_URL=http://localhost:3003
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mcp-web-manager
    restart: unless-stopped
    profiles:
      - production

volumes:
  data:
  logs:
  config:
