[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmd = '''
npm ci
cd client && npm ci
cd ../server && npm ci
'''

[phases.build]
cmd = '''
npm run build:client
'''

[start]
cmd = "cd client && npm start" 